### ISSUE TITLE
German Umlaute in 

### ISSUE THREAD

**Issue by nevrion** [galacticat/booksonic-library-editor#1]
Hello
Unfortunately, I lack the ability to solve my problem myself.

In the file desc.txt, umlauts such as äüö are shown only cryptically.
However, they work wonderfully in the reader.txt file.

sorry for my bad English

**Comment by galacticat** [comment]
I gave no thought to foreign characters when I threw this together. It needs a function to determine the file reader based on a selector. I may find time early next week to look at it. But basically anywhere in the code where I am reading a file it should specify the file formatting.

**Comment by galacticat** [comment]
Ok, I updated the readers to use Encoding.Default. I tested with the "äüö" characters and found that the Narrator box being a text box was not saving the reader.txt file as plaintext, so I added a quick function that saves it to a Ritch Text box, and then saves it to a file. I think this will fix this issue. Version 1.2 uploaded.

**Comment by nevrion** [comment]
Thank you so mutch.

**Comment by nevrion** [comment]
Unfortunately, the reader.txt is now empty. In the desc.txt also umlauts do not continue to work. Unlike the reader.txt, desc.txt is also not saved in UTF-8.

I hope I express myself reasonably understandable.

Thank you for your help.

**Comment by nevrion** [comment]
Hi, is there anything new about this problem?

**Comment by galacticat** [comment]
I believe this issue is resolved in version 2.0. I made some other fun enhancements too.

**Comment by nevrion** [comment]
Now everything seems to work. Many Thanks :)

**Comment by galacticat** [comment]
Closing since it is fixed.
